/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuidesNutritionForHybridAthletesRouteImport } from './routes/guides.nutrition-for-hybrid-athletes'
import { Route as GuidesLegDayAndFootballRouteImport } from './routes/guides.leg-day-and-football'
import { Route as GuidesHybridTrainingSplitsRouteImport } from './routes/guides.hybrid-training-splits'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedSportRouteImport } from './routes/_authenticated/sport'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedScanRouteImport } from './routes/_authenticated/scan'
import { Route as AuthenticatedPlanRouteImport } from './routes/_authenticated/plan'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedNutritionRouteImport } from './routes/_authenticated/nutrition'
import { Route as AuthenticatedJournalRouteImport } from './routes/_authenticated/journal'
import { Route as AuthenticatedInvitesRouteImport } from './routes/_authenticated/invites'
import { Route as AuthenticatedInsightsRouteImport } from './routes/_authenticated/insights'
import { Route as AuthenticatedGymRouteImport } from './routes/_authenticated/gym'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCheckinRouteImport } from './routes/_authenticated/checkin'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedSportIdRouteImport } from './routes/_authenticated/sport.$id'
import { Route as AuthenticatedGymIdRouteImport } from './routes/_authenticated/gym.$id'
import { Route as AuthenticatedChatIdRouteImport } from './routes/_authenticated/chat.$id'
import { Route as AuthenticatedAthletesIdRouteImport } from './routes/_authenticated/athletes.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesNutritionForHybridAthletesRoute =
  GuidesNutritionForHybridAthletesRouteImport.update({
    id: '/guides/nutrition-for-hybrid-athletes',
    path: '/guides/nutrition-for-hybrid-athletes',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuidesLegDayAndFootballRoute = GuidesLegDayAndFootballRouteImport.update({
  id: '/guides/leg-day-and-football',
  path: '/guides/leg-day-and-football',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesHybridTrainingSplitsRoute =
  GuidesHybridTrainingSplitsRouteImport.update({
    id: '/guides/hybrid-training-splits',
    path: '/guides/hybrid-training-splits',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSportRoute = AuthenticatedSportRouteImport.update({
  id: '/sport',
  path: '/sport',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScanRoute = AuthenticatedScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlanRoute = AuthenticatedPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNutritionRoute = AuthenticatedNutritionRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJournalRoute = AuthenticatedJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvitesRoute = AuthenticatedInvitesRouteImport.update({
  id: '/invites',
  path: '/invites',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInsightsRoute = AuthenticatedInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGymRoute = AuthenticatedGymRouteImport.update({
  id: '/gym',
  path: '/gym',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCheckinRoute = AuthenticatedCheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSportIdRoute = AuthenticatedSportIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedSportRoute,
} as any)
const AuthenticatedGymIdRoute = AuthenticatedGymIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedGymRoute,
} as any)
const AuthenticatedChatIdRoute = AuthenticatedChatIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedChatRoute,
} as any)
const AuthenticatedAthletesIdRoute = AuthenticatedAthletesIdRouteImport.update({
  id: '/athletes/$id',
  path: '/athletes/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof AuthenticatedChatRouteWithChildren
  '/checkin': typeof AuthenticatedCheckinRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/gym': typeof AuthenticatedGymRouteWithChildren
  '/insights': typeof AuthenticatedInsightsRoute
  '/invites': typeof AuthenticatedInvitesRoute
  '/journal': typeof AuthenticatedJournalRoute
  '/nutrition': typeof AuthenticatedNutritionRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/plan': typeof AuthenticatedPlanRoute
  '/scan': typeof AuthenticatedScanRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sport': typeof AuthenticatedSportRouteWithChildren
  '/team': typeof AuthenticatedTeamRoute
  '/guides/hybrid-training-splits': typeof GuidesHybridTrainingSplitsRoute
  '/guides/leg-day-and-football': typeof GuidesLegDayAndFootballRoute
  '/guides/nutrition-for-hybrid-athletes': typeof GuidesNutritionForHybridAthletesRoute
  '/athletes/$id': typeof AuthenticatedAthletesIdRoute
  '/chat/$id': typeof AuthenticatedChatIdRoute
  '/gym/$id': typeof AuthenticatedGymIdRoute
  '/sport/$id': typeof AuthenticatedSportIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof AuthenticatedChatRouteWithChildren
  '/checkin': typeof AuthenticatedCheckinRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/gym': typeof AuthenticatedGymRouteWithChildren
  '/insights': typeof AuthenticatedInsightsRoute
  '/invites': typeof AuthenticatedInvitesRoute
  '/journal': typeof AuthenticatedJournalRoute
  '/nutrition': typeof AuthenticatedNutritionRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/plan': typeof AuthenticatedPlanRoute
  '/scan': typeof AuthenticatedScanRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sport': typeof AuthenticatedSportRouteWithChildren
  '/team': typeof AuthenticatedTeamRoute
  '/guides/hybrid-training-splits': typeof GuidesHybridTrainingSplitsRoute
  '/guides/leg-day-and-football': typeof GuidesLegDayAndFootballRoute
  '/guides/nutrition-for-hybrid-athletes': typeof GuidesNutritionForHybridAthletesRoute
  '/athletes/$id': typeof AuthenticatedAthletesIdRoute
  '/chat/$id': typeof AuthenticatedChatIdRoute
  '/gym/$id': typeof AuthenticatedGymIdRoute
  '/sport/$id': typeof AuthenticatedSportIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/chat': typeof AuthenticatedChatRouteWithChildren
  '/_authenticated/checkin': typeof AuthenticatedCheckinRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/gym': typeof AuthenticatedGymRouteWithChildren
  '/_authenticated/insights': typeof AuthenticatedInsightsRoute
  '/_authenticated/invites': typeof AuthenticatedInvitesRoute
  '/_authenticated/journal': typeof AuthenticatedJournalRoute
  '/_authenticated/nutrition': typeof AuthenticatedNutritionRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/plan': typeof AuthenticatedPlanRoute
  '/_authenticated/scan': typeof AuthenticatedScanRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/sport': typeof AuthenticatedSportRouteWithChildren
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/guides/hybrid-training-splits': typeof GuidesHybridTrainingSplitsRoute
  '/guides/leg-day-and-football': typeof GuidesLegDayAndFootballRoute
  '/guides/nutrition-for-hybrid-athletes': typeof GuidesNutritionForHybridAthletesRoute
  '/_authenticated/athletes/$id': typeof AuthenticatedAthletesIdRoute
  '/_authenticated/chat/$id': typeof AuthenticatedChatIdRoute
  '/_authenticated/gym/$id': typeof AuthenticatedGymIdRoute
  '/_authenticated/sport/$id': typeof AuthenticatedSportIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/chat'
    | '/checkin'
    | '/dashboard'
    | '/gym'
    | '/insights'
    | '/invites'
    | '/journal'
    | '/nutrition'
    | '/onboarding'
    | '/plan'
    | '/scan'
    | '/settings'
    | '/sport'
    | '/team'
    | '/guides/hybrid-training-splits'
    | '/guides/leg-day-and-football'
    | '/guides/nutrition-for-hybrid-athletes'
    | '/athletes/$id'
    | '/chat/$id'
    | '/gym/$id'
    | '/sport/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/chat'
    | '/checkin'
    | '/dashboard'
    | '/gym'
    | '/insights'
    | '/invites'
    | '/journal'
    | '/nutrition'
    | '/onboarding'
    | '/plan'
    | '/scan'
    | '/settings'
    | '/sport'
    | '/team'
    | '/guides/hybrid-training-splits'
    | '/guides/leg-day-and-football'
    | '/guides/nutrition-for-hybrid-athletes'
    | '/athletes/$id'
    | '/chat/$id'
    | '/gym/$id'
    | '/sport/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/chat'
    | '/_authenticated/checkin'
    | '/_authenticated/dashboard'
    | '/_authenticated/gym'
    | '/_authenticated/insights'
    | '/_authenticated/invites'
    | '/_authenticated/journal'
    | '/_authenticated/nutrition'
    | '/_authenticated/onboarding'
    | '/_authenticated/plan'
    | '/_authenticated/scan'
    | '/_authenticated/settings'
    | '/_authenticated/sport'
    | '/_authenticated/team'
    | '/guides/hybrid-training-splits'
    | '/guides/leg-day-and-football'
    | '/guides/nutrition-for-hybrid-athletes'
    | '/_authenticated/athletes/$id'
    | '/_authenticated/chat/$id'
    | '/_authenticated/gym/$id'
    | '/_authenticated/sport/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  GuidesHybridTrainingSplitsRoute: typeof GuidesHybridTrainingSplitsRoute
  GuidesLegDayAndFootballRoute: typeof GuidesLegDayAndFootballRoute
  GuidesNutritionForHybridAthletesRoute: typeof GuidesNutritionForHybridAthletesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/nutrition-for-hybrid-athletes': {
      id: '/guides/nutrition-for-hybrid-athletes'
      path: '/guides/nutrition-for-hybrid-athletes'
      fullPath: '/guides/nutrition-for-hybrid-athletes'
      preLoaderRoute: typeof GuidesNutritionForHybridAthletesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/leg-day-and-football': {
      id: '/guides/leg-day-and-football'
      path: '/guides/leg-day-and-football'
      fullPath: '/guides/leg-day-and-football'
      preLoaderRoute: typeof GuidesLegDayAndFootballRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/hybrid-training-splits': {
      id: '/guides/hybrid-training-splits'
      path: '/guides/hybrid-training-splits'
      fullPath: '/guides/hybrid-training-splits'
      preLoaderRoute: typeof GuidesHybridTrainingSplitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sport': {
      id: '/_authenticated/sport'
      path: '/sport'
      fullPath: '/sport'
      preLoaderRoute: typeof AuthenticatedSportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scan': {
      id: '/_authenticated/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof AuthenticatedScanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plan': {
      id: '/_authenticated/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof AuthenticatedPlanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nutrition': {
      id: '/_authenticated/nutrition'
      path: '/nutrition'
      fullPath: '/nutrition'
      preLoaderRoute: typeof AuthenticatedNutritionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/journal': {
      id: '/_authenticated/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof AuthenticatedJournalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invites': {
      id: '/_authenticated/invites'
      path: '/invites'
      fullPath: '/invites'
      preLoaderRoute: typeof AuthenticatedInvitesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/insights': {
      id: '/_authenticated/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AuthenticatedInsightsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gym': {
      id: '/_authenticated/gym'
      path: '/gym'
      fullPath: '/gym'
      preLoaderRoute: typeof AuthenticatedGymRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checkin': {
      id: '/_authenticated/checkin'
      path: '/checkin'
      fullPath: '/checkin'
      preLoaderRoute: typeof AuthenticatedCheckinRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sport/$id': {
      id: '/_authenticated/sport/$id'
      path: '/$id'
      fullPath: '/sport/$id'
      preLoaderRoute: typeof AuthenticatedSportIdRouteImport
      parentRoute: typeof AuthenticatedSportRoute
    }
    '/_authenticated/gym/$id': {
      id: '/_authenticated/gym/$id'
      path: '/$id'
      fullPath: '/gym/$id'
      preLoaderRoute: typeof AuthenticatedGymIdRouteImport
      parentRoute: typeof AuthenticatedGymRoute
    }
    '/_authenticated/chat/$id': {
      id: '/_authenticated/chat/$id'
      path: '/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof AuthenticatedChatIdRouteImport
      parentRoute: typeof AuthenticatedChatRoute
    }
    '/_authenticated/athletes/$id': {
      id: '/_authenticated/athletes/$id'
      path: '/athletes/$id'
      fullPath: '/athletes/$id'
      preLoaderRoute: typeof AuthenticatedAthletesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedChatRouteChildren {
  AuthenticatedChatIdRoute: typeof AuthenticatedChatIdRoute
}

const AuthenticatedChatRouteChildren: AuthenticatedChatRouteChildren = {
  AuthenticatedChatIdRoute: AuthenticatedChatIdRoute,
}

const AuthenticatedChatRouteWithChildren =
  AuthenticatedChatRoute._addFileChildren(AuthenticatedChatRouteChildren)

interface AuthenticatedGymRouteChildren {
  AuthenticatedGymIdRoute: typeof AuthenticatedGymIdRoute
}

const AuthenticatedGymRouteChildren: AuthenticatedGymRouteChildren = {
  AuthenticatedGymIdRoute: AuthenticatedGymIdRoute,
}

const AuthenticatedGymRouteWithChildren =
  AuthenticatedGymRoute._addFileChildren(AuthenticatedGymRouteChildren)

interface AuthenticatedSportRouteChildren {
  AuthenticatedSportIdRoute: typeof AuthenticatedSportIdRoute
}

const AuthenticatedSportRouteChildren: AuthenticatedSportRouteChildren = {
  AuthenticatedSportIdRoute: AuthenticatedSportIdRoute,
}

const AuthenticatedSportRouteWithChildren =
  AuthenticatedSportRoute._addFileChildren(AuthenticatedSportRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedChatRoute: typeof AuthenticatedChatRouteWithChildren
  AuthenticatedCheckinRoute: typeof AuthenticatedCheckinRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGymRoute: typeof AuthenticatedGymRouteWithChildren
  AuthenticatedInsightsRoute: typeof AuthenticatedInsightsRoute
  AuthenticatedInvitesRoute: typeof AuthenticatedInvitesRoute
  AuthenticatedJournalRoute: typeof AuthenticatedJournalRoute
  AuthenticatedNutritionRoute: typeof AuthenticatedNutritionRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPlanRoute: typeof AuthenticatedPlanRoute
  AuthenticatedScanRoute: typeof AuthenticatedScanRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSportRoute: typeof AuthenticatedSportRouteWithChildren
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedAthletesIdRoute: typeof AuthenticatedAthletesIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedChatRoute: AuthenticatedChatRouteWithChildren,
  AuthenticatedCheckinRoute: AuthenticatedCheckinRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGymRoute: AuthenticatedGymRouteWithChildren,
  AuthenticatedInsightsRoute: AuthenticatedInsightsRoute,
  AuthenticatedInvitesRoute: AuthenticatedInvitesRoute,
  AuthenticatedJournalRoute: AuthenticatedJournalRoute,
  AuthenticatedNutritionRoute: AuthenticatedNutritionRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPlanRoute: AuthenticatedPlanRoute,
  AuthenticatedScanRoute: AuthenticatedScanRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSportRoute: AuthenticatedSportRouteWithChildren,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedAthletesIdRoute: AuthenticatedAthletesIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  GuidesHybridTrainingSplitsRoute: GuidesHybridTrainingSplitsRoute,
  GuidesLegDayAndFootballRoute: GuidesLegDayAndFootballRoute,
  GuidesNutritionForHybridAthletesRoute: GuidesNutritionForHybridAthletesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
