/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JoinTokenRouteImport } from './routes/join.$token'
import { Route as GuidesSupplementsForHybridAthletesRouteImport } from './routes/guides.supplements-for-hybrid-athletes'
import { Route as GuidesRunningAndLegDayRouteImport } from './routes/guides.running-and-leg-day'
import { Route as GuidesNutritionForHybridAthletesRouteImport } from './routes/guides.nutrition-for-hybrid-athletes'
import { Route as GuidesLegDayAndFootballRouteImport } from './routes/guides.leg-day-and-football'
import { Route as GuidesHybridTrainingSplitsRouteImport } from './routes/guides.hybrid-training-splits'
import { Route as Guides12WeekProgramRouteImport } from './routes/guides.12-week-program'
import { Route as AuthenticatedTriathlonRouteImport } from './routes/_authenticated/triathlon'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedScanRouteImport } from './routes/_authenticated/scan'
import { Route as AuthenticatedRecordsRouteImport } from './routes/_authenticated/records'
import { Route as AuthenticatedPrivacyRouteImport } from './routes/_authenticated/privacy'
import { Route as AuthenticatedPlanRouteImport } from './routes/_authenticated/plan'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedNutritionRouteImport } from './routes/_authenticated/nutrition'
import { Route as AuthenticatedMatchdayRouteImport } from './routes/_authenticated/matchday'
import { Route as AuthenticatedLeaderboardRouteImport } from './routes/_authenticated/leaderboard'
import { Route as AuthenticatedJournalRouteImport } from './routes/_authenticated/journal'
import { Route as AuthenticatedInvitesRouteImport } from './routes/_authenticated/invites'
import { Route as AuthenticatedInsightsRouteImport } from './routes/_authenticated/insights'
import { Route as AuthenticatedImportRouteImport } from './routes/_authenticated/import'
import { Route as AuthenticatedEquipmentRouteImport } from './routes/_authenticated/equipment'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCheckinRouteImport } from './routes/_authenticated/checkin'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AuthenticatedSportIndexRouteImport } from './routes/_authenticated/sport.index'
import { Route as AuthenticatedRacesIndexRouteImport } from './routes/_authenticated/races.index'
import { Route as AuthenticatedGymIndexRouteImport } from './routes/_authenticated/gym.index'
import { Route as AuthenticatedCoursesIndexRouteImport } from './routes/_authenticated/courses.index'
import { Route as AuthenticatedChatIndexRouteImport } from './routes/_authenticated/chat.index'
import { Route as AuthenticatedActivitiesIndexRouteImport } from './routes/_authenticated/activities.index'
import { Route as AuthenticatedSportIdRouteImport } from './routes/_authenticated/sport.$id'
import { Route as AuthenticatedRacesIdRouteImport } from './routes/_authenticated/races.$id'
import { Route as AuthenticatedGymIdRouteImport } from './routes/_authenticated/gym.$id'
import { Route as AuthenticatedCoursesIdRouteImport } from './routes/_authenticated/courses.$id'
import { Route as AuthenticatedChatIdRouteImport } from './routes/_authenticated/chat.$id'
import { Route as AuthenticatedAthletesIdRouteImport } from './routes/_authenticated/athletes.$id'
import { Route as AuthenticatedActivitiesIdRouteImport } from './routes/_authenticated/activities.$id'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinTokenRoute = JoinTokenRouteImport.update({
  id: '/join/$token',
  path: '/join/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesSupplementsForHybridAthletesRoute =
  GuidesSupplementsForHybridAthletesRouteImport.update({
    id: '/guides/supplements-for-hybrid-athletes',
    path: '/guides/supplements-for-hybrid-athletes',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuidesRunningAndLegDayRoute = GuidesRunningAndLegDayRouteImport.update({
  id: '/guides/running-and-leg-day',
  path: '/guides/running-and-leg-day',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesNutritionForHybridAthletesRoute =
  GuidesNutritionForHybridAthletesRouteImport.update({
    id: '/guides/nutrition-for-hybrid-athletes',
    path: '/guides/nutrition-for-hybrid-athletes',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuidesLegDayAndFootballRoute = GuidesLegDayAndFootballRouteImport.update({
  id: '/guides/leg-day-and-football',
  path: '/guides/leg-day-and-football',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesHybridTrainingSplitsRoute =
  GuidesHybridTrainingSplitsRouteImport.update({
    id: '/guides/hybrid-training-splits',
    path: '/guides/hybrid-training-splits',
    getParentRoute: () => rootRouteImport,
  } as any)
const Guides12WeekProgramRoute = Guides12WeekProgramRouteImport.update({
  id: '/guides/12-week-program',
  path: '/guides/12-week-program',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTriathlonRoute = AuthenticatedTriathlonRouteImport.update({
  id: '/triathlon',
  path: '/triathlon',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScanRoute = AuthenticatedScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRecordsRoute = AuthenticatedRecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPrivacyRoute = AuthenticatedPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlanRoute = AuthenticatedPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNutritionRoute = AuthenticatedNutritionRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMatchdayRoute = AuthenticatedMatchdayRouteImport.update({
  id: '/matchday',
  path: '/matchday',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeaderboardRoute =
  AuthenticatedLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedJournalRoute = AuthenticatedJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvitesRoute = AuthenticatedInvitesRouteImport.update({
  id: '/invites',
  path: '/invites',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInsightsRoute = AuthenticatedInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImportRoute = AuthenticatedImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEquipmentRoute = AuthenticatedEquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCheckinRoute = AuthenticatedCheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedSportIndexRoute = AuthenticatedSportIndexRouteImport.update({
  id: '/sport/',
  path: '/sport/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRacesIndexRoute = AuthenticatedRacesIndexRouteImport.update({
  id: '/races/',
  path: '/races/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGymIndexRoute = AuthenticatedGymIndexRouteImport.update({
  id: '/gym/',
  path: '/gym/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCoursesIndexRoute =
  AuthenticatedCoursesIndexRouteImport.update({
    id: '/courses/',
    path: '/courses/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatIndexRoute = AuthenticatedChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedActivitiesIndexRoute =
  AuthenticatedActivitiesIndexRouteImport.update({
    id: '/activities/',
    path: '/activities/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSportIdRoute = AuthenticatedSportIdRouteImport.update({
  id: '/sport/$id',
  path: '/sport/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRacesIdRoute = AuthenticatedRacesIdRouteImport.update({
  id: '/races/$id',
  path: '/races/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGymIdRoute = AuthenticatedGymIdRouteImport.update({
  id: '/gym/$id',
  path: '/gym/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCoursesIdRoute = AuthenticatedCoursesIdRouteImport.update({
  id: '/courses/$id',
  path: '/courses/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatIdRoute = AuthenticatedChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAthletesIdRoute = AuthenticatedAthletesIdRouteImport.update({
  id: '/athletes/$id',
  path: '/athletes/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedActivitiesIdRoute =
  AuthenticatedActivitiesIdRouteImport.update({
    id: '/activities/$id',
    path: '/activities/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/checkin': typeof AuthenticatedCheckinRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/equipment': typeof AuthenticatedEquipmentRoute
  '/import': typeof AuthenticatedImportRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/invites': typeof AuthenticatedInvitesRoute
  '/journal': typeof AuthenticatedJournalRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/matchday': typeof AuthenticatedMatchdayRoute
  '/nutrition': typeof AuthenticatedNutritionRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/plan': typeof AuthenticatedPlanRoute
  '/privacy': typeof AuthenticatedPrivacyRoute
  '/records': typeof AuthenticatedRecordsRoute
  '/scan': typeof AuthenticatedScanRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/triathlon': typeof AuthenticatedTriathlonRoute
  '/guides/12-week-program': typeof Guides12WeekProgramRoute
  '/guides/hybrid-training-splits': typeof GuidesHybridTrainingSplitsRoute
  '/guides/leg-day-and-football': typeof GuidesLegDayAndFootballRoute
  '/guides/nutrition-for-hybrid-athletes': typeof GuidesNutritionForHybridAthletesRoute
  '/guides/running-and-leg-day': typeof GuidesRunningAndLegDayRoute
  '/guides/supplements-for-hybrid-athletes': typeof GuidesSupplementsForHybridAthletesRoute
  '/join/$token': typeof JoinTokenRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/activities/$id': typeof AuthenticatedActivitiesIdRoute
  '/athletes/$id': typeof AuthenticatedAthletesIdRoute
  '/chat/$id': typeof AuthenticatedChatIdRoute
  '/courses/$id': typeof AuthenticatedCoursesIdRoute
  '/gym/$id': typeof AuthenticatedGymIdRoute
  '/races/$id': typeof AuthenticatedRacesIdRoute
  '/sport/$id': typeof AuthenticatedSportIdRoute
  '/activities/': typeof AuthenticatedActivitiesIndexRoute
  '/chat/': typeof AuthenticatedChatIndexRoute
  '/courses/': typeof AuthenticatedCoursesIndexRoute
  '/gym/': typeof AuthenticatedGymIndexRoute
  '/races/': typeof AuthenticatedRacesIndexRoute
  '/sport/': typeof AuthenticatedSportIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/checkin': typeof AuthenticatedCheckinRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/equipment': typeof AuthenticatedEquipmentRoute
  '/import': typeof AuthenticatedImportRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/invites': typeof AuthenticatedInvitesRoute
  '/journal': typeof AuthenticatedJournalRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/matchday': typeof AuthenticatedMatchdayRoute
  '/nutrition': typeof AuthenticatedNutritionRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/plan': typeof AuthenticatedPlanRoute
  '/privacy': typeof AuthenticatedPrivacyRoute
  '/records': typeof AuthenticatedRecordsRoute
  '/scan': typeof AuthenticatedScanRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/triathlon': typeof AuthenticatedTriathlonRoute
  '/guides/12-week-program': typeof Guides12WeekProgramRoute
  '/guides/hybrid-training-splits': typeof GuidesHybridTrainingSplitsRoute
  '/guides/leg-day-and-football': typeof GuidesLegDayAndFootballRoute
  '/guides/nutrition-for-hybrid-athletes': typeof GuidesNutritionForHybridAthletesRoute
  '/guides/running-and-leg-day': typeof GuidesRunningAndLegDayRoute
  '/guides/supplements-for-hybrid-athletes': typeof GuidesSupplementsForHybridAthletesRoute
  '/join/$token': typeof JoinTokenRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/activities/$id': typeof AuthenticatedActivitiesIdRoute
  '/athletes/$id': typeof AuthenticatedAthletesIdRoute
  '/chat/$id': typeof AuthenticatedChatIdRoute
  '/courses/$id': typeof AuthenticatedCoursesIdRoute
  '/gym/$id': typeof AuthenticatedGymIdRoute
  '/races/$id': typeof AuthenticatedRacesIdRoute
  '/sport/$id': typeof AuthenticatedSportIdRoute
  '/activities': typeof AuthenticatedActivitiesIndexRoute
  '/chat': typeof AuthenticatedChatIndexRoute
  '/courses': typeof AuthenticatedCoursesIndexRoute
  '/gym': typeof AuthenticatedGymIndexRoute
  '/races': typeof AuthenticatedRacesIndexRoute
  '/sport': typeof AuthenticatedSportIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/checkin': typeof AuthenticatedCheckinRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/equipment': typeof AuthenticatedEquipmentRoute
  '/_authenticated/import': typeof AuthenticatedImportRoute
  '/_authenticated/insights': typeof AuthenticatedInsightsRoute
  '/_authenticated/invites': typeof AuthenticatedInvitesRoute
  '/_authenticated/journal': typeof AuthenticatedJournalRoute
  '/_authenticated/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/_authenticated/matchday': typeof AuthenticatedMatchdayRoute
  '/_authenticated/nutrition': typeof AuthenticatedNutritionRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/plan': typeof AuthenticatedPlanRoute
  '/_authenticated/privacy': typeof AuthenticatedPrivacyRoute
  '/_authenticated/records': typeof AuthenticatedRecordsRoute
  '/_authenticated/scan': typeof AuthenticatedScanRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/_authenticated/triathlon': typeof AuthenticatedTriathlonRoute
  '/guides/12-week-program': typeof Guides12WeekProgramRoute
  '/guides/hybrid-training-splits': typeof GuidesHybridTrainingSplitsRoute
  '/guides/leg-day-and-football': typeof GuidesLegDayAndFootballRoute
  '/guides/nutrition-for-hybrid-athletes': typeof GuidesNutritionForHybridAthletesRoute
  '/guides/running-and-leg-day': typeof GuidesRunningAndLegDayRoute
  '/guides/supplements-for-hybrid-athletes': typeof GuidesSupplementsForHybridAthletesRoute
  '/join/$token': typeof JoinTokenRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/activities/$id': typeof AuthenticatedActivitiesIdRoute
  '/_authenticated/athletes/$id': typeof AuthenticatedAthletesIdRoute
  '/_authenticated/chat/$id': typeof AuthenticatedChatIdRoute
  '/_authenticated/courses/$id': typeof AuthenticatedCoursesIdRoute
  '/_authenticated/gym/$id': typeof AuthenticatedGymIdRoute
  '/_authenticated/races/$id': typeof AuthenticatedRacesIdRoute
  '/_authenticated/sport/$id': typeof AuthenticatedSportIdRoute
  '/_authenticated/activities/': typeof AuthenticatedActivitiesIndexRoute
  '/_authenticated/chat/': typeof AuthenticatedChatIndexRoute
  '/_authenticated/courses/': typeof AuthenticatedCoursesIndexRoute
  '/_authenticated/gym/': typeof AuthenticatedGymIndexRoute
  '/_authenticated/races/': typeof AuthenticatedRacesIndexRoute
  '/_authenticated/sport/': typeof AuthenticatedSportIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/analytics'
    | '/checkin'
    | '/dashboard'
    | '/equipment'
    | '/import'
    | '/insights'
    | '/invites'
    | '/journal'
    | '/leaderboard'
    | '/matchday'
    | '/nutrition'
    | '/onboarding'
    | '/plan'
    | '/privacy'
    | '/records'
    | '/scan'
    | '/settings'
    | '/team'
    | '/triathlon'
    | '/guides/12-week-program'
    | '/guides/hybrid-training-splits'
    | '/guides/leg-day-and-football'
    | '/guides/nutrition-for-hybrid-athletes'
    | '/guides/running-and-leg-day'
    | '/guides/supplements-for-hybrid-athletes'
    | '/join/$token'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/activities/$id'
    | '/athletes/$id'
    | '/chat/$id'
    | '/courses/$id'
    | '/gym/$id'
    | '/races/$id'
    | '/sport/$id'
    | '/activities/'
    | '/chat/'
    | '/courses/'
    | '/gym/'
    | '/races/'
    | '/sport/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/analytics'
    | '/checkin'
    | '/dashboard'
    | '/equipment'
    | '/import'
    | '/insights'
    | '/invites'
    | '/journal'
    | '/leaderboard'
    | '/matchday'
    | '/nutrition'
    | '/onboarding'
    | '/plan'
    | '/privacy'
    | '/records'
    | '/scan'
    | '/settings'
    | '/team'
    | '/triathlon'
    | '/guides/12-week-program'
    | '/guides/hybrid-training-splits'
    | '/guides/leg-day-and-football'
    | '/guides/nutrition-for-hybrid-athletes'
    | '/guides/running-and-leg-day'
    | '/guides/supplements-for-hybrid-athletes'
    | '/join/$token'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/activities/$id'
    | '/athletes/$id'
    | '/chat/$id'
    | '/courses/$id'
    | '/gym/$id'
    | '/races/$id'
    | '/sport/$id'
    | '/activities'
    | '/chat'
    | '/courses'
    | '/gym'
    | '/races'
    | '/sport'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/analytics'
    | '/_authenticated/checkin'
    | '/_authenticated/dashboard'
    | '/_authenticated/equipment'
    | '/_authenticated/import'
    | '/_authenticated/insights'
    | '/_authenticated/invites'
    | '/_authenticated/journal'
    | '/_authenticated/leaderboard'
    | '/_authenticated/matchday'
    | '/_authenticated/nutrition'
    | '/_authenticated/onboarding'
    | '/_authenticated/plan'
    | '/_authenticated/privacy'
    | '/_authenticated/records'
    | '/_authenticated/scan'
    | '/_authenticated/settings'
    | '/_authenticated/team'
    | '/_authenticated/triathlon'
    | '/guides/12-week-program'
    | '/guides/hybrid-training-splits'
    | '/guides/leg-day-and-football'
    | '/guides/nutrition-for-hybrid-athletes'
    | '/guides/running-and-leg-day'
    | '/guides/supplements-for-hybrid-athletes'
    | '/join/$token'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/activities/$id'
    | '/_authenticated/athletes/$id'
    | '/_authenticated/chat/$id'
    | '/_authenticated/courses/$id'
    | '/_authenticated/gym/$id'
    | '/_authenticated/races/$id'
    | '/_authenticated/sport/$id'
    | '/_authenticated/activities/'
    | '/_authenticated/chat/'
    | '/_authenticated/courses/'
    | '/_authenticated/gym/'
    | '/_authenticated/races/'
    | '/_authenticated/sport/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  Guides12WeekProgramRoute: typeof Guides12WeekProgramRoute
  GuidesHybridTrainingSplitsRoute: typeof GuidesHybridTrainingSplitsRoute
  GuidesLegDayAndFootballRoute: typeof GuidesLegDayAndFootballRoute
  GuidesNutritionForHybridAthletesRoute: typeof GuidesNutritionForHybridAthletesRoute
  GuidesRunningAndLegDayRoute: typeof GuidesRunningAndLegDayRoute
  GuidesSupplementsForHybridAthletesRoute: typeof GuidesSupplementsForHybridAthletesRoute
  JoinTokenRoute: typeof JoinTokenRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$token': {
      id: '/join/$token'
      path: '/join/$token'
      fullPath: '/join/$token'
      preLoaderRoute: typeof JoinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/supplements-for-hybrid-athletes': {
      id: '/guides/supplements-for-hybrid-athletes'
      path: '/guides/supplements-for-hybrid-athletes'
      fullPath: '/guides/supplements-for-hybrid-athletes'
      preLoaderRoute: typeof GuidesSupplementsForHybridAthletesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/running-and-leg-day': {
      id: '/guides/running-and-leg-day'
      path: '/guides/running-and-leg-day'
      fullPath: '/guides/running-and-leg-day'
      preLoaderRoute: typeof GuidesRunningAndLegDayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/nutrition-for-hybrid-athletes': {
      id: '/guides/nutrition-for-hybrid-athletes'
      path: '/guides/nutrition-for-hybrid-athletes'
      fullPath: '/guides/nutrition-for-hybrid-athletes'
      preLoaderRoute: typeof GuidesNutritionForHybridAthletesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/leg-day-and-football': {
      id: '/guides/leg-day-and-football'
      path: '/guides/leg-day-and-football'
      fullPath: '/guides/leg-day-and-football'
      preLoaderRoute: typeof GuidesLegDayAndFootballRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/hybrid-training-splits': {
      id: '/guides/hybrid-training-splits'
      path: '/guides/hybrid-training-splits'
      fullPath: '/guides/hybrid-training-splits'
      preLoaderRoute: typeof GuidesHybridTrainingSplitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/12-week-program': {
      id: '/guides/12-week-program'
      path: '/guides/12-week-program'
      fullPath: '/guides/12-week-program'
      preLoaderRoute: typeof Guides12WeekProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/triathlon': {
      id: '/_authenticated/triathlon'
      path: '/triathlon'
      fullPath: '/triathlon'
      preLoaderRoute: typeof AuthenticatedTriathlonRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scan': {
      id: '/_authenticated/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof AuthenticatedScanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/records': {
      id: '/_authenticated/records'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof AuthenticatedRecordsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/privacy': {
      id: '/_authenticated/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof AuthenticatedPrivacyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plan': {
      id: '/_authenticated/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof AuthenticatedPlanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nutrition': {
      id: '/_authenticated/nutrition'
      path: '/nutrition'
      fullPath: '/nutrition'
      preLoaderRoute: typeof AuthenticatedNutritionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/matchday': {
      id: '/_authenticated/matchday'
      path: '/matchday'
      fullPath: '/matchday'
      preLoaderRoute: typeof AuthenticatedMatchdayRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leaderboard': {
      id: '/_authenticated/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthenticatedLeaderboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/journal': {
      id: '/_authenticated/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof AuthenticatedJournalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invites': {
      id: '/_authenticated/invites'
      path: '/invites'
      fullPath: '/invites'
      preLoaderRoute: typeof AuthenticatedInvitesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/insights': {
      id: '/_authenticated/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AuthenticatedInsightsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/import': {
      id: '/_authenticated/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AuthenticatedImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipment': {
      id: '/_authenticated/equipment'
      path: '/equipment'
      fullPath: '/equipment'
      preLoaderRoute: typeof AuthenticatedEquipmentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checkin': {
      id: '/_authenticated/checkin'
      path: '/checkin'
      fullPath: '/checkin'
      preLoaderRoute: typeof AuthenticatedCheckinRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sport/': {
      id: '/_authenticated/sport/'
      path: '/sport'
      fullPath: '/sport/'
      preLoaderRoute: typeof AuthenticatedSportIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/races/': {
      id: '/_authenticated/races/'
      path: '/races'
      fullPath: '/races/'
      preLoaderRoute: typeof AuthenticatedRacesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gym/': {
      id: '/_authenticated/gym/'
      path: '/gym'
      fullPath: '/gym/'
      preLoaderRoute: typeof AuthenticatedGymIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/courses/': {
      id: '/_authenticated/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof AuthenticatedCoursesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat/': {
      id: '/_authenticated/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof AuthenticatedChatIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/activities/': {
      id: '/_authenticated/activities/'
      path: '/activities'
      fullPath: '/activities/'
      preLoaderRoute: typeof AuthenticatedActivitiesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sport/$id': {
      id: '/_authenticated/sport/$id'
      path: '/sport/$id'
      fullPath: '/sport/$id'
      preLoaderRoute: typeof AuthenticatedSportIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/races/$id': {
      id: '/_authenticated/races/$id'
      path: '/races/$id'
      fullPath: '/races/$id'
      preLoaderRoute: typeof AuthenticatedRacesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gym/$id': {
      id: '/_authenticated/gym/$id'
      path: '/gym/$id'
      fullPath: '/gym/$id'
      preLoaderRoute: typeof AuthenticatedGymIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/courses/$id': {
      id: '/_authenticated/courses/$id'
      path: '/courses/$id'
      fullPath: '/courses/$id'
      preLoaderRoute: typeof AuthenticatedCoursesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat/$id': {
      id: '/_authenticated/chat/$id'
      path: '/chat/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof AuthenticatedChatIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/athletes/$id': {
      id: '/_authenticated/athletes/$id'
      path: '/athletes/$id'
      fullPath: '/athletes/$id'
      preLoaderRoute: typeof AuthenticatedAthletesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/activities/$id': {
      id: '/_authenticated/activities/$id'
      path: '/activities/$id'
      fullPath: '/activities/$id'
      preLoaderRoute: typeof AuthenticatedActivitiesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedCheckinRoute: typeof AuthenticatedCheckinRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEquipmentRoute: typeof AuthenticatedEquipmentRoute
  AuthenticatedImportRoute: typeof AuthenticatedImportRoute
  AuthenticatedInsightsRoute: typeof AuthenticatedInsightsRoute
  AuthenticatedInvitesRoute: typeof AuthenticatedInvitesRoute
  AuthenticatedJournalRoute: typeof AuthenticatedJournalRoute
  AuthenticatedLeaderboardRoute: typeof AuthenticatedLeaderboardRoute
  AuthenticatedMatchdayRoute: typeof AuthenticatedMatchdayRoute
  AuthenticatedNutritionRoute: typeof AuthenticatedNutritionRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPlanRoute: typeof AuthenticatedPlanRoute
  AuthenticatedPrivacyRoute: typeof AuthenticatedPrivacyRoute
  AuthenticatedRecordsRoute: typeof AuthenticatedRecordsRoute
  AuthenticatedScanRoute: typeof AuthenticatedScanRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedTriathlonRoute: typeof AuthenticatedTriathlonRoute
  AuthenticatedActivitiesIdRoute: typeof AuthenticatedActivitiesIdRoute
  AuthenticatedAthletesIdRoute: typeof AuthenticatedAthletesIdRoute
  AuthenticatedChatIdRoute: typeof AuthenticatedChatIdRoute
  AuthenticatedCoursesIdRoute: typeof AuthenticatedCoursesIdRoute
  AuthenticatedGymIdRoute: typeof AuthenticatedGymIdRoute
  AuthenticatedRacesIdRoute: typeof AuthenticatedRacesIdRoute
  AuthenticatedSportIdRoute: typeof AuthenticatedSportIdRoute
  AuthenticatedActivitiesIndexRoute: typeof AuthenticatedActivitiesIndexRoute
  AuthenticatedChatIndexRoute: typeof AuthenticatedChatIndexRoute
  AuthenticatedCoursesIndexRoute: typeof AuthenticatedCoursesIndexRoute
  AuthenticatedGymIndexRoute: typeof AuthenticatedGymIndexRoute
  AuthenticatedRacesIndexRoute: typeof AuthenticatedRacesIndexRoute
  AuthenticatedSportIndexRoute: typeof AuthenticatedSportIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedCheckinRoute: AuthenticatedCheckinRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEquipmentRoute: AuthenticatedEquipmentRoute,
  AuthenticatedImportRoute: AuthenticatedImportRoute,
  AuthenticatedInsightsRoute: AuthenticatedInsightsRoute,
  AuthenticatedInvitesRoute: AuthenticatedInvitesRoute,
  AuthenticatedJournalRoute: AuthenticatedJournalRoute,
  AuthenticatedLeaderboardRoute: AuthenticatedLeaderboardRoute,
  AuthenticatedMatchdayRoute: AuthenticatedMatchdayRoute,
  AuthenticatedNutritionRoute: AuthenticatedNutritionRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPlanRoute: AuthenticatedPlanRoute,
  AuthenticatedPrivacyRoute: AuthenticatedPrivacyRoute,
  AuthenticatedRecordsRoute: AuthenticatedRecordsRoute,
  AuthenticatedScanRoute: AuthenticatedScanRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedTriathlonRoute: AuthenticatedTriathlonRoute,
  AuthenticatedActivitiesIdRoute: AuthenticatedActivitiesIdRoute,
  AuthenticatedAthletesIdRoute: AuthenticatedAthletesIdRoute,
  AuthenticatedChatIdRoute: AuthenticatedChatIdRoute,
  AuthenticatedCoursesIdRoute: AuthenticatedCoursesIdRoute,
  AuthenticatedGymIdRoute: AuthenticatedGymIdRoute,
  AuthenticatedRacesIdRoute: AuthenticatedRacesIdRoute,
  AuthenticatedSportIdRoute: AuthenticatedSportIdRoute,
  AuthenticatedActivitiesIndexRoute: AuthenticatedActivitiesIndexRoute,
  AuthenticatedChatIndexRoute: AuthenticatedChatIndexRoute,
  AuthenticatedCoursesIndexRoute: AuthenticatedCoursesIndexRoute,
  AuthenticatedGymIndexRoute: AuthenticatedGymIndexRoute,
  AuthenticatedRacesIndexRoute: AuthenticatedRacesIndexRoute,
  AuthenticatedSportIndexRoute: AuthenticatedSportIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  Guides12WeekProgramRoute: Guides12WeekProgramRoute,
  GuidesHybridTrainingSplitsRoute: GuidesHybridTrainingSplitsRoute,
  GuidesLegDayAndFootballRoute: GuidesLegDayAndFootballRoute,
  GuidesNutritionForHybridAthletesRoute: GuidesNutritionForHybridAthletesRoute,
  GuidesRunningAndLegDayRoute: GuidesRunningAndLegDayRoute,
  GuidesSupplementsForHybridAthletesRoute:
    GuidesSupplementsForHybridAthletesRoute,
  JoinTokenRoute: JoinTokenRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
